version: '3'
services:
  backend:
    build: ./backend
    # command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./.env.dev
  frontend:
    build: ./frontend
  nginx:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./src:/usr/share/nginx/html
