version: '3'
services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - 8000:8000
  frontend:
    build: ./frontend
    command: "serve -n -p 3000 -s ."
    depends_on:
      - backend
    volumes:
      - front_volume:/app/static
    expose:
      - 3000
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - front_volume:/app/front
    ports:
      - 80:80
    depends_on:
      - frontend

volumes:
  media_volume:
  static_volume:
  front_volume:
