# Generated by Django 3.2.15 on 2022-08-16 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_comments_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
